<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        if (DB::table('users')->count() > 0) {
            $this->command->info('Tabel users sudah berisi data. Seeder dilewati.');
            return;
        }

        DB::table('barang')->insert([
            [
                'id' => 7,
                'kodebarang' => 'BRG00007',
                'nama' => 'Bayam',
                'kategori' => 'Sayuran',
                'satuan' => 'Pcs',
                'stok_minimum' => 5,
                'stok' => 0,
            ],
            [
                'id' => 8,
                'kodebarang' => 'BRG00008',
                'nama' => 'Bawang',
                'kategori' => 'Bumbu',
                'satuan' => 'Pcs',
                'stok_minimum' => 5,
                'stok' => 0,
            ],
            [
                'id' => 9,
                'kodebarang' => 'BRG00009',
                'nama' => 'ayam',
                'kategori' => 'Daging',
                'satuan' => 'Kg',
                'stok_minimum' => 5,
                'stok' => 0,
            ],
            [
                'id' => 10,
                'kodebarang' => 'BRG00010',
                'nama' => 'Sapi',
                'kategori' => 'Daging',
                'satuan' => 'Kg',
                'stok_minimum' => 5,
                'stok' => 0,
            ],
            [
                'id' => 11,
                'kodebarang' => 'BRG00011',
                'nama' => 'Tomat',
                'kategori' => 'Sayuran',
                'satuan' => 'Kg',
                'stok_minimum' => 5,
                'stok' => 0,
            ],
            [
                'id' => 12,
                'kodebarang' => 'BRG00012',
                'nama' => 'Gula Pasir',
                'kategori' => 'Bumbu',
                'satuan' => 'Kg',
                'stok_minimum' => 5,
                'stok' => 0,
            ],
            [
                'id' => 14,
                'kodebarang' => 'BRG00014',
                'nama' => 'toge',
                'kategori' => 'Sayuran',
                'satuan' => 'Pack',
                'stok_minimum' => 5,
                'stok' => 0,
            ],
            [
                'id' => 15,
                'kodebarang' => 'BRG00015',
                'nama' => 'cabe kering',
                'kategori' => 'Sayuran',
                'satuan' => 'Kg',
                'stok_minimum' => 5,
                'stok' => 0,
            ],
            [
                'id' => 16,
                'kodebarang' => 'BRG00016',
                'nama' => 'masako',
                'kategori' => 'Bumbu',
                'satuan' => 'Pcs',
                'stok_minimum' => 5,
                'stok' => 0,
            ],
            [
                'id' => 17,
                'kodebarang' => 'BRG00017',
                'nama' => 'garam',
                'kategori' => 'Bumbu',
                'satuan' => 'Pcs',
                'stok_minimum' => 5,
                'stok' => 0,
            ],
            [
                'id' => 18,
                'kodebarang' => 'BRG00018',
                'nama' => 'kecap',
                'kategori' => 'Bumbu',
                'satuan' => 'Pack',
                'stok_minimum' => 5,
                'stok' => 0,
            ],
            [
                'id' => 19,
                'kodebarang' => 'BRG00019',
                'nama' => 'nangka',
                'kategori' => 'Sayuran',
                'satuan' => 'Pack',
                'stok_minimum' => 5,
                'stok' => 0,
            ],
            [
                'id' => 20,
                'kodebarang' => 'BRG00020',
                'nama' => 'beras',
                'kategori' => 'Bahan Pokok',
                'satuan' => 'Karung',
                'stok_minimum' => 5,
                'stok' => 0,
            ],
        ]);

        DB::table('cabang')->insert([
            [
                'id' => 1,
                'nama' => 'Cabang Sungai Jawi',
            ],
            [
                'id' => 2,
                'nama' => 'Cabang Siantan',
            ],
            [
                'id' => 3,
                'nama' => 'Cabang M.Sohor',
            ],
            [
                'id' => 4,
                'nama' => 'Cabang Serdam',
            ],
            [
                'id' => 5,
                'nama' => 'Cabang Desa Kapur',
            ],
            [
                'id' => 6,
                'nama' => 'Cabang Ambawang',
            ],
            [
                'id' => 7,
                'nama' => 'Cabang Kota Baru',
            ],
            [
                'id' => 8,
                'nama' => 'Cabang Jeruju',
            ],
        ]);

        DB::table('permintaan')->insert([
            [
                'id' => 4,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Diterima',
                'catatan' => null,
                'created_at' => '2026-06-15 17:45:53',
                'updated_at' => '2026-06-15 17:46:31',
            ],
            [
                'id' => 5,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Diterima',
                'catatan' => 'coy',
                'created_at' => '2026-06-15 22:22:06',
                'updated_at' => '2026-06-15 22:54:31',
            ],
            [
                'id' => 6,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Ditolak',
                'catatan' => 'rrr',
                'created_at' => '2026-06-15 22:59:43',
                'updated_at' => '2026-06-15 23:00:20',
            ],
            [
                'id' => 7,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Diterima',
                'catatan' => 'ok',
                'created_at' => '2026-06-16 07:50:27',
                'updated_at' => '2026-06-16 07:51:06',
            ],
            [
                'id' => 8,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Diterima',
                'catatan' => 'ok',
                'created_at' => '2026-06-16 07:53:21',
                'updated_at' => '2026-06-16 07:53:46',
            ],
            [
                'id' => 9,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Diterima',
                'catatan' => 'boy',
                'created_at' => '2026-06-17 16:04:38',
                'updated_at' => '2026-06-17 16:05:17',
            ],
            [
                'id' => 10,
                'cabang_id' => 2,
                'user_id' => 5,
                'status' => 'Diterima',
                'catatan' => 'boyy',
                'created_at' => '2026-06-17 16:13:46',
                'updated_at' => '2026-06-17 16:14:17',
            ],
            [
                'id' => 11,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Diterima',
                'catatan' => null,
                'created_at' => '2026-06-17 20:03:51',
                'updated_at' => '2026-06-17 21:44:54',
            ],
            [
                'id' => 12,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Diterima',
                'catatan' => 'oyy cok',
                'created_at' => '2026-06-17 22:36:10',
                'updated_at' => '2026-06-17 22:56:00',
            ],
            [
                'id' => 13,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Ditolak',
                'catatan' => 'woy',
                'created_at' => '2026-06-17 22:44:46',
                'updated_at' => '2026-06-17 22:54:19',
            ],
            [
                'id' => 14,
                'cabang_id' => 3,
                'user_id' => 6,
                'status' => 'Diterima',
                'catatan' => null,
                'created_at' => '2026-06-18 01:17:26',
                'updated_at' => '2026-06-18 01:20:08',
            ],
            [
                'id' => 15,
                'cabang_id' => 3,
                'user_id' => 6,
                'status' => 'Diterima',
                'catatan' => 'makasih',
                'created_at' => '2026-06-18 01:18:08',
                'updated_at' => '2026-06-18 01:19:03',
            ],
            [
                'id' => 16,
                'cabang_id' => 3,
                'user_id' => 6,
                'status' => 'Diterima',
                'catatan' => null,
                'created_at' => '2026-06-18 01:32:30',
                'updated_at' => '2026-06-18 01:32:59',
            ],
            [
                'id' => 17,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Diterima',
                'catatan' => 'pliss',
                'created_at' => '2026-06-18 03:14:02',
                'updated_at' => '2026-06-18 03:14:51',
            ],
            [
                'id' => 18,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Diterima',
                'catatan' => null,
                'created_at' => '2026-06-18 04:47:10',
                'updated_at' => '2026-06-18 04:50:53',
            ],
            [
                'id' => 19,
                'cabang_id' => 2,
                'user_id' => 5,
                'status' => 'Ditolak',
                'catatan' => 'boyyy',
                'created_at' => '2026-06-18 04:48:13',
                'updated_at' => '2026-06-18 04:50:15',
            ],
            [
                'id' => 20,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Ditolak',
                'catatan' => 'lesgooo',
                'created_at' => '2026-06-18 10:43:13',
                'updated_at' => '2026-06-19 14:36:26',
            ],
            [
                'id' => 21,
                'cabang_id' => 3,
                'user_id' => 6,
                'status' => 'Diterima',
                'catatan' => 'hahah',
                'created_at' => '2026-06-18 10:44:47',
                'updated_at' => '2026-06-18 13:21:10',
            ],
            [
                'id' => 22,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Diterima',
                'catatan' => 'dd',
                'created_at' => '2026-06-18 13:33:42',
                'updated_at' => '2026-06-18 13:34:37',
            ],
            [
                'id' => 23,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Diterima',
                'catatan' => 'cepat boy',
                'created_at' => '2026-06-19 14:56:51',
                'updated_at' => '2026-06-19 19:29:50',
            ],
            [
                'id' => 24,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Diterima',
                'catatan' => 'mintak boy',
                'created_at' => '2026-06-19 19:32:01',
                'updated_at' => '2026-06-19 19:32:59',
            ],
            [
                'id' => 25,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Diterima',
                'catatan' => 'jjkkk',
                'created_at' => '2026-06-20 09:40:34',
                'updated_at' => '2026-06-20 09:49:44',
            ],
            [
                'id' => 26,
                'cabang_id' => 2,
                'user_id' => 5,
                'status' => 'Diterima',
                'catatan' => 'yaboy',
                'created_at' => '2026-06-20 09:59:57',
                'updated_at' => '2026-06-20 10:00:33',
            ],
            [
                'id' => 27,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Ditolak',
                'catatan' => 'hah',
                'created_at' => '2026-06-20 10:05:33',
                'updated_at' => '2026-06-20 10:06:10',
            ],
            [
                'id' => 28,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Diterima',
                'catatan' => 'fff',
                'created_at' => '2026-06-20 11:07:05',
                'updated_at' => '2026-06-20 11:07:37',
            ],
            [
                'id' => 29,
                'cabang_id' => 3,
                'user_id' => 6,
                'status' => 'Diterima',
                'catatan' => 'ya',
                'created_at' => '2026-06-20 11:54:56',
                'updated_at' => '2026-06-20 11:55:23',
            ],
            [
                'id' => 30,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Diterima',
                'catatan' => 'minta ya boy',
                'created_at' => '2026-06-20 12:32:08',
                'updated_at' => '2026-06-20 12:32:57',
            ],
            [
                'id' => 31,
                'cabang_id' => 7,
                'user_id' => 7,
                'status' => 'Diterima',
                'catatan' => 'kirim ya boy',
                'created_at' => '2026-06-20 13:39:32',
                'updated_at' => '2026-06-20 13:40:33',
            ],
            [
                'id' => 32,
                'cabang_id' => 7,
                'user_id' => 7,
                'status' => 'Diterima',
                'catatan' => 'kirim boy',
                'created_at' => '2026-06-20 13:59:32',
                'updated_at' => '2026-06-20 14:00:14',
            ],
            [
                'id' => 33,
                'cabang_id' => 7,
                'user_id' => 7,
                'status' => 'Menunggu Konfirmasi',
                'catatan' => 'Haloo',
                'created_at' => '2026-06-21 11:25:02',
                'updated_at' => '2026-06-21 11:25:02',
            ],
            [
                'id' => 34,
                'cabang_id' => 1,
                'user_id' => 2,
                'status' => 'Ditolak',
                'catatan' => 'mm',
                'created_at' => '2026-06-21 15:05:05',
                'updated_at' => '2026-06-21 16:12:43',
            ],
            [
                'id' => 36,
                'cabang_id' => 7,
                'user_id' => 7,
                'status' => 'Menunggu Konfirmasi',
                'catatan' => 'pliiss',
                'created_at' => '2026-06-22 15:33:09',
                'updated_at' => '2026-06-22 15:33:09',
            ],
            [
                'id' => 37,
                'cabang_id' => 7,
                'user_id' => 7,
                'status' => 'Menunggu Konfirmasi',
                'catatan' => 'hy',
                'created_at' => '2026-06-22 15:39:46',
                'updated_at' => '2026-06-22 15:39:46',
            ],
            [
                'id' => 38,
                'cabang_id' => 7,
                'user_id' => 7,
                'status' => 'Diterima',
                'catatan' => 'hy',
                'created_at' => '2026-06-22 15:46:27',
                'updated_at' => '2026-06-22 16:07:26',
            ],
            [
                'id' => 39,
                'cabang_id' => 7,
                'user_id' => 7,
                'status' => 'Diterima',
                'catatan' => 'kirim ya boyy',
                'created_at' => '2026-06-26 14:10:50',
                'updated_at' => '2026-06-26 14:11:30',
            ],
        ]);

        DB::table('permintaandetail')->insert([
            [
                'id' => 7,
                'permintaan_id' => 4,
                'barang_id' => 8,
                'jumlah' => 20,
            ],
            [
                'id' => 8,
                'permintaan_id' => 4,
                'barang_id' => 7,
                'jumlah' => 20,
            ],
            [
                'id' => 9,
                'permintaan_id' => 5,
                'barang_id' => 8,
                'jumlah' => 2,
            ],
            [
                'id' => 10,
                'permintaan_id' => 6,
                'barang_id' => 7,
                'jumlah' => 1,
            ],
            [
                'id' => 11,
                'permintaan_id' => 7,
                'barang_id' => 9,
                'jumlah' => 50,
            ],
            [
                'id' => 12,
                'permintaan_id' => 8,
                'barang_id' => 10,
                'jumlah' => 50,
            ],
            [
                'id' => 13,
                'permintaan_id' => 9,
                'barang_id' => 9,
                'jumlah' => 50,
            ],
            [
                'id' => 14,
                'permintaan_id' => 10,
                'barang_id' => 9,
                'jumlah' => 300,
            ],
            [
                'id' => 15,
                'permintaan_id' => 11,
                'barang_id' => 8,
                'jumlah' => 5,
            ],
            [
                'id' => 16,
                'permintaan_id' => 12,
                'barang_id' => 12,
                'jumlah' => 10,
            ],
            [
                'id' => 17,
                'permintaan_id' => 13,
                'barang_id' => 12,
                'jumlah' => 10,
            ],
            [
                'id' => 18,
                'permintaan_id' => 14,
                'barang_id' => 19,
                'jumlah' => 50,
            ],
            [
                'id' => 19,
                'permintaan_id' => 14,
                'barang_id' => 16,
                'jumlah' => 50,
            ],
            [
                'id' => 20,
                'permintaan_id' => 15,
                'barang_id' => 9,
                'jumlah' => 10,
            ],
            [
                'id' => 21,
                'permintaan_id' => 16,
                'barang_id' => 8,
                'jumlah' => 50,
            ],
            [
                'id' => 22,
                'permintaan_id' => 17,
                'barang_id' => 7,
                'jumlah' => 5,
            ],
            [
                'id' => 23,
                'permintaan_id' => 18,
                'barang_id' => 11,
                'jumlah' => 50,
            ],
            [
                'id' => 24,
                'permintaan_id' => 19,
                'barang_id' => 18,
                'jumlah' => 5,
            ],
            [
                'id' => 25,
                'permintaan_id' => 20,
                'barang_id' => 15,
                'jumlah' => 50,
            ],
            [
                'id' => 26,
                'permintaan_id' => 20,
                'barang_id' => 12,
                'jumlah' => 20,
            ],
            [
                'id' => 27,
                'permintaan_id' => 21,
                'barang_id' => 10,
                'jumlah' => 30,
            ],
            [
                'id' => 28,
                'permintaan_id' => 21,
                'barang_id' => 15,
                'jumlah' => 20,
            ],
            [
                'id' => 29,
                'permintaan_id' => 21,
                'barang_id' => 11,
                'jumlah' => 20,
            ],
            [
                'id' => 30,
                'permintaan_id' => 22,
                'barang_id' => 19,
                'jumlah' => 1,
            ],
            [
                'id' => 31,
                'permintaan_id' => 23,
                'barang_id' => 12,
                'jumlah' => 15,
            ],
            [
                'id' => 32,
                'permintaan_id' => 24,
                'barang_id' => 10,
                'jumlah' => 500,
            ],
            [
                'id' => 33,
                'permintaan_id' => 25,
                'barang_id' => 10,
                'jumlah' => 90,
            ],
            [
                'id' => 34,
                'permintaan_id' => 26,
                'barang_id' => 17,
                'jumlah' => 100,
            ],
            [
                'id' => 35,
                'permintaan_id' => 26,
                'barang_id' => 14,
                'jumlah' => 50,
            ],
            [
                'id' => 36,
                'permintaan_id' => 26,
                'barang_id' => 10,
                'jumlah' => 10,
            ],
            [
                'id' => 37,
                'permintaan_id' => 27,
                'barang_id' => 9,
                'jumlah' => 10,
            ],
            [
                'id' => 38,
                'permintaan_id' => 28,
                'barang_id' => 9,
                'jumlah' => 5,
            ],
            [
                'id' => 39,
                'permintaan_id' => 29,
                'barang_id' => 12,
                'jumlah' => 50,
            ],
            [
                'id' => 40,
                'permintaan_id' => 30,
                'barang_id' => 12,
                'jumlah' => 100,
            ],
            [
                'id' => 41,
                'permintaan_id' => 30,
                'barang_id' => 16,
                'jumlah' => 100,
            ],
            [
                'id' => 42,
                'permintaan_id' => 31,
                'barang_id' => 20,
                'jumlah' => 10,
            ],
            [
                'id' => 43,
                'permintaan_id' => 31,
                'barang_id' => 9,
                'jumlah' => 20,
            ],
            [
                'id' => 44,
                'permintaan_id' => 32,
                'barang_id' => 10,
                'jumlah' => 100,
            ],
            [
                'id' => 45,
                'permintaan_id' => 32,
                'barang_id' => 18,
                'jumlah' => 50,
            ],
            [
                'id' => 46,
                'permintaan_id' => 33,
                'barang_id' => 10,
                'jumlah' => 100,
            ],
            [
                'id' => 47,
                'permintaan_id' => 33,
                'barang_id' => 16,
                'jumlah' => 30,
            ],
            [
                'id' => 48,
                'permintaan_id' => 33,
                'barang_id' => 15,
                'jumlah' => 20,
            ],
            [
                'id' => 49,
                'permintaan_id' => 34,
                'barang_id' => 8,
                'jumlah' => 1,
            ],
            [
                'id' => 50,
                'permintaan_id' => 35,
                'barang_id' => 16,
                'jumlah' => 100,
            ],
            [
                'id' => 51,
                'permintaan_id' => 36,
                'barang_id' => 16,
                'jumlah' => 100,
            ],
            [
                'id' => 52,
                'permintaan_id' => 37,
                'barang_id' => 10,
                'jumlah' => 10,
            ],
            [
                'id' => 53,
                'permintaan_id' => 38,
                'barang_id' => 12,
                'jumlah' => 5,
            ],
            [
                'id' => 54,
                'permintaan_id' => 38,
                'barang_id' => 16,
                'jumlah' => 10,
            ],
            [
                'id' => 55,
                'permintaan_id' => 38,
                'barang_id' => 10,
                'jumlah' => 15,
            ],
            [
                'id' => 56,
                'permintaan_id' => 39,
                'barang_id' => 10,
                'jumlah' => 10,
            ],
        ]);

        DB::table('stokcabang')->insert([
            [
                'id' => 7,
                'cabang_id' => 1,
                'barang_id' => 7,
                'jumlah' => 15,
                'created_at' => '2026-06-15 17:44:19',
                'updated_at' => '2026-06-18 03:14:51',
            ],
            [
                'id' => 8,
                'cabang_id' => 2,
                'barang_id' => 7,
                'jumlah' => 0,
                'created_at' => '2026-06-15 17:44:19',
                'updated_at' => '2026-06-15 17:44:19',
            ],
            [
                'id' => 9,
                'cabang_id' => 1,
                'barang_id' => 8,
                'jumlah' => 17,
                'created_at' => '2026-06-15 17:44:31',
                'updated_at' => '2026-06-17 21:44:54',
            ],
            [
                'id' => 10,
                'cabang_id' => 2,
                'barang_id' => 8,
                'jumlah' => 0,
                'created_at' => '2026-06-15 17:44:31',
                'updated_at' => '2026-06-15 17:44:31',
            ],
            [
                'id' => 11,
                'cabang_id' => 1,
                'barang_id' => 9,
                'jumlah' => 105,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-20 11:07:37',
            ],
            [
                'id' => 12,
                'cabang_id' => 2,
                'barang_id' => 9,
                'jumlah' => 300,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-17 16:14:17',
            ],
            [
                'id' => 13,
                'cabang_id' => 3,
                'barang_id' => 7,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-16 07:40:37',
            ],
            [
                'id' => 14,
                'cabang_id' => 3,
                'barang_id' => 8,
                'jumlah' => 50,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-18 01:32:59',
            ],
            [
                'id' => 15,
                'cabang_id' => 3,
                'barang_id' => 9,
                'jumlah' => 10,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-18 01:19:03',
            ],
            [
                'id' => 16,
                'cabang_id' => 4,
                'barang_id' => 7,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-16 07:40:37',
            ],
            [
                'id' => 17,
                'cabang_id' => 4,
                'barang_id' => 8,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-16 07:40:37',
            ],
            [
                'id' => 18,
                'cabang_id' => 4,
                'barang_id' => 9,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-16 07:40:37',
            ],
            [
                'id' => 19,
                'cabang_id' => 5,
                'barang_id' => 7,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-16 07:40:37',
            ],
            [
                'id' => 20,
                'cabang_id' => 5,
                'barang_id' => 8,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-16 07:40:37',
            ],
            [
                'id' => 21,
                'cabang_id' => 5,
                'barang_id' => 9,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-16 07:40:37',
            ],
            [
                'id' => 22,
                'cabang_id' => 6,
                'barang_id' => 7,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-16 07:40:37',
            ],
            [
                'id' => 23,
                'cabang_id' => 6,
                'barang_id' => 8,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-16 07:40:37',
            ],
            [
                'id' => 24,
                'cabang_id' => 6,
                'barang_id' => 9,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-16 07:40:37',
            ],
            [
                'id' => 25,
                'cabang_id' => 7,
                'barang_id' => 7,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-16 07:40:37',
            ],
            [
                'id' => 26,
                'cabang_id' => 7,
                'barang_id' => 8,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-16 07:40:37',
            ],
            [
                'id' => 27,
                'cabang_id' => 7,
                'barang_id' => 9,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-20 13:58:55',
            ],
            [
                'id' => 28,
                'cabang_id' => 8,
                'barang_id' => 7,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-16 07:40:37',
            ],
            [
                'id' => 29,
                'cabang_id' => 8,
                'barang_id' => 8,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-16 07:40:37',
            ],
            [
                'id' => 30,
                'cabang_id' => 8,
                'barang_id' => 9,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-16 07:40:37',
            ],
            [
                'id' => 31,
                'cabang_id' => 1,
                'barang_id' => 10,
                'jumlah' => 600,
                'created_at' => '2026-06-16 07:41:51',
                'updated_at' => '2026-06-20 11:45:48',
            ],
            [
                'id' => 32,
                'cabang_id' => 2,
                'barang_id' => 10,
                'jumlah' => 10,
                'created_at' => '2026-06-16 07:41:51',
                'updated_at' => '2026-06-20 10:00:33',
            ],
            [
                'id' => 33,
                'cabang_id' => 3,
                'barang_id' => 10,
                'jumlah' => 30,
                'created_at' => '2026-06-16 07:41:51',
                'updated_at' => '2026-06-18 13:21:10',
            ],
            [
                'id' => 34,
                'cabang_id' => 4,
                'barang_id' => 10,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:41:51',
                'updated_at' => '2026-06-16 07:41:51',
            ],
            [
                'id' => 35,
                'cabang_id' => 5,
                'barang_id' => 10,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:41:51',
                'updated_at' => '2026-06-16 07:41:51',
            ],
            [
                'id' => 36,
                'cabang_id' => 6,
                'barang_id' => 10,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:41:51',
                'updated_at' => '2026-06-16 07:41:51',
            ],
            [
                'id' => 37,
                'cabang_id' => 7,
                'barang_id' => 10,
                'jumlah' => 110,
                'created_at' => '2026-06-16 07:41:51',
                'updated_at' => '2026-06-26 14:11:30',
            ],
            [
                'id' => 38,
                'cabang_id' => 8,
                'barang_id' => 10,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:41:51',
                'updated_at' => '2026-06-16 07:41:51',
            ],
            [
                'id' => 39,
                'cabang_id' => 1,
                'barang_id' => 11,
                'jumlah' => 50,
                'created_at' => '2026-06-16 07:42:48',
                'updated_at' => '2026-06-18 04:50:53',
            ],
            [
                'id' => 40,
                'cabang_id' => 2,
                'barang_id' => 11,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:42:48',
                'updated_at' => '2026-06-16 07:42:48',
            ],
            [
                'id' => 41,
                'cabang_id' => 3,
                'barang_id' => 11,
                'jumlah' => 20,
                'created_at' => '2026-06-16 07:42:48',
                'updated_at' => '2026-06-18 13:21:10',
            ],
            [
                'id' => 42,
                'cabang_id' => 4,
                'barang_id' => 11,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:42:48',
                'updated_at' => '2026-06-16 07:42:48',
            ],
            [
                'id' => 43,
                'cabang_id' => 5,
                'barang_id' => 11,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:42:48',
                'updated_at' => '2026-06-16 07:42:48',
            ],
            [
                'id' => 44,
                'cabang_id' => 6,
                'barang_id' => 11,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:42:48',
                'updated_at' => '2026-06-16 07:42:48',
            ],
            [
                'id' => 45,
                'cabang_id' => 7,
                'barang_id' => 11,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:42:48',
                'updated_at' => '2026-06-16 07:42:48',
            ],
            [
                'id' => 46,
                'cabang_id' => 8,
                'barang_id' => 11,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:42:48',
                'updated_at' => '2026-06-16 07:42:48',
            ],
            [
                'id' => 47,
                'cabang_id' => 1,
                'barang_id' => 12,
                'jumlah' => 120,
                'created_at' => '2026-06-16 07:43:23',
                'updated_at' => '2026-06-20 12:32:57',
            ],
            [
                'id' => 48,
                'cabang_id' => 2,
                'barang_id' => 12,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:43:23',
                'updated_at' => '2026-06-16 07:43:23',
            ],
            [
                'id' => 49,
                'cabang_id' => 3,
                'barang_id' => 12,
                'jumlah' => 50,
                'created_at' => '2026-06-16 07:43:23',
                'updated_at' => '2026-06-20 11:55:23',
            ],
            [
                'id' => 50,
                'cabang_id' => 4,
                'barang_id' => 12,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:43:23',
                'updated_at' => '2026-06-16 07:43:23',
            ],
            [
                'id' => 51,
                'cabang_id' => 5,
                'barang_id' => 12,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:43:23',
                'updated_at' => '2026-06-16 07:43:23',
            ],
            [
                'id' => 52,
                'cabang_id' => 6,
                'barang_id' => 12,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:43:23',
                'updated_at' => '2026-06-16 07:43:23',
            ],
            [
                'id' => 53,
                'cabang_id' => 7,
                'barang_id' => 12,
                'jumlah' => 5,
                'created_at' => '2026-06-16 07:43:23',
                'updated_at' => '2026-06-22 16:07:26',
            ],
            [
                'id' => 54,
                'cabang_id' => 8,
                'barang_id' => 12,
                'jumlah' => 0,
                'created_at' => '2026-06-16 07:43:23',
                'updated_at' => '2026-06-16 07:43:23',
            ],
            [
                'id' => 63,
                'cabang_id' => 1,
                'barang_id' => 14,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:56:21',
                'updated_at' => '2026-06-18 00:56:21',
            ],
            [
                'id' => 64,
                'cabang_id' => 2,
                'barang_id' => 14,
                'jumlah' => 50,
                'created_at' => '2026-06-18 00:56:21',
                'updated_at' => '2026-06-20 10:00:33',
            ],
            [
                'id' => 65,
                'cabang_id' => 3,
                'barang_id' => 14,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:56:21',
                'updated_at' => '2026-06-18 00:56:21',
            ],
            [
                'id' => 66,
                'cabang_id' => 4,
                'barang_id' => 14,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:56:21',
                'updated_at' => '2026-06-18 00:56:21',
            ],
            [
                'id' => 67,
                'cabang_id' => 5,
                'barang_id' => 14,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:56:21',
                'updated_at' => '2026-06-18 00:56:21',
            ],
            [
                'id' => 68,
                'cabang_id' => 6,
                'barang_id' => 14,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:56:21',
                'updated_at' => '2026-06-18 00:56:21',
            ],
            [
                'id' => 69,
                'cabang_id' => 7,
                'barang_id' => 14,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:56:21',
                'updated_at' => '2026-06-18 00:56:21',
            ],
            [
                'id' => 70,
                'cabang_id' => 8,
                'barang_id' => 14,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:56:21',
                'updated_at' => '2026-06-18 00:56:21',
            ],
            [
                'id' => 71,
                'cabang_id' => 1,
                'barang_id' => 15,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:56:55',
                'updated_at' => '2026-06-18 00:56:55',
            ],
            [
                'id' => 72,
                'cabang_id' => 2,
                'barang_id' => 15,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:56:55',
                'updated_at' => '2026-06-18 00:56:55',
            ],
            [
                'id' => 73,
                'cabang_id' => 3,
                'barang_id' => 15,
                'jumlah' => 20,
                'created_at' => '2026-06-18 00:56:55',
                'updated_at' => '2026-06-18 13:21:10',
            ],
            [
                'id' => 74,
                'cabang_id' => 4,
                'barang_id' => 15,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:56:55',
                'updated_at' => '2026-06-18 00:56:55',
            ],
            [
                'id' => 75,
                'cabang_id' => 5,
                'barang_id' => 15,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:56:55',
                'updated_at' => '2026-06-18 00:56:55',
            ],
            [
                'id' => 76,
                'cabang_id' => 6,
                'barang_id' => 15,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:56:55',
                'updated_at' => '2026-06-18 00:56:55',
            ],
            [
                'id' => 77,
                'cabang_id' => 7,
                'barang_id' => 15,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:56:55',
                'updated_at' => '2026-06-18 00:56:55',
            ],
            [
                'id' => 78,
                'cabang_id' => 8,
                'barang_id' => 15,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:56:55',
                'updated_at' => '2026-06-18 00:56:55',
            ],
            [
                'id' => 79,
                'cabang_id' => 1,
                'barang_id' => 16,
                'jumlah' => 100,
                'created_at' => '2026-06-18 00:57:43',
                'updated_at' => '2026-06-20 12:32:57',
            ],
            [
                'id' => 80,
                'cabang_id' => 2,
                'barang_id' => 16,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:57:43',
                'updated_at' => '2026-06-18 00:57:43',
            ],
            [
                'id' => 81,
                'cabang_id' => 3,
                'barang_id' => 16,
                'jumlah' => 50,
                'created_at' => '2026-06-18 00:57:43',
                'updated_at' => '2026-06-18 01:20:08',
            ],
            [
                'id' => 82,
                'cabang_id' => 4,
                'barang_id' => 16,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:57:43',
                'updated_at' => '2026-06-18 00:57:43',
            ],
            [
                'id' => 83,
                'cabang_id' => 5,
                'barang_id' => 16,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:57:43',
                'updated_at' => '2026-06-18 00:57:43',
            ],
            [
                'id' => 84,
                'cabang_id' => 6,
                'barang_id' => 16,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:57:43',
                'updated_at' => '2026-06-18 00:57:43',
            ],
            [
                'id' => 85,
                'cabang_id' => 7,
                'barang_id' => 16,
                'jumlah' => 10,
                'created_at' => '2026-06-18 00:57:43',
                'updated_at' => '2026-06-22 16:07:26',
            ],
            [
                'id' => 86,
                'cabang_id' => 8,
                'barang_id' => 16,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:57:43',
                'updated_at' => '2026-06-18 00:57:43',
            ],
            [
                'id' => 87,
                'cabang_id' => 1,
                'barang_id' => 17,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:58:09',
                'updated_at' => '2026-06-18 00:58:09',
            ],
            [
                'id' => 88,
                'cabang_id' => 2,
                'barang_id' => 17,
                'jumlah' => 100,
                'created_at' => '2026-06-18 00:58:09',
                'updated_at' => '2026-06-20 10:00:33',
            ],
            [
                'id' => 89,
                'cabang_id' => 3,
                'barang_id' => 17,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:58:09',
                'updated_at' => '2026-06-18 00:58:09',
            ],
            [
                'id' => 90,
                'cabang_id' => 4,
                'barang_id' => 17,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:58:10',
                'updated_at' => '2026-06-18 00:58:10',
            ],
            [
                'id' => 91,
                'cabang_id' => 5,
                'barang_id' => 17,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:58:10',
                'updated_at' => '2026-06-18 00:58:10',
            ],
            [
                'id' => 92,
                'cabang_id' => 6,
                'barang_id' => 17,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:58:10',
                'updated_at' => '2026-06-18 00:58:10',
            ],
            [
                'id' => 93,
                'cabang_id' => 7,
                'barang_id' => 17,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:58:10',
                'updated_at' => '2026-06-18 00:58:10',
            ],
            [
                'id' => 94,
                'cabang_id' => 8,
                'barang_id' => 17,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:58:10',
                'updated_at' => '2026-06-18 00:58:10',
            ],
            [
                'id' => 95,
                'cabang_id' => 1,
                'barang_id' => 18,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:59:11',
                'updated_at' => '2026-06-18 00:59:11',
            ],
            [
                'id' => 96,
                'cabang_id' => 2,
                'barang_id' => 18,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:59:11',
                'updated_at' => '2026-06-18 00:59:11',
            ],
            [
                'id' => 97,
                'cabang_id' => 3,
                'barang_id' => 18,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:59:11',
                'updated_at' => '2026-06-18 00:59:11',
            ],
            [
                'id' => 98,
                'cabang_id' => 4,
                'barang_id' => 18,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:59:12',
                'updated_at' => '2026-06-18 00:59:12',
            ],
            [
                'id' => 99,
                'cabang_id' => 5,
                'barang_id' => 18,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:59:12',
                'updated_at' => '2026-06-18 00:59:12',
            ],
            [
                'id' => 100,
                'cabang_id' => 6,
                'barang_id' => 18,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:59:12',
                'updated_at' => '2026-06-18 00:59:12',
            ],
            [
                'id' => 101,
                'cabang_id' => 7,
                'barang_id' => 18,
                'jumlah' => 10,
                'created_at' => '2026-06-18 00:59:12',
                'updated_at' => '2026-06-23 12:23:01',
            ],
            [
                'id' => 102,
                'cabang_id' => 8,
                'barang_id' => 18,
                'jumlah' => 0,
                'created_at' => '2026-06-18 00:59:12',
                'updated_at' => '2026-06-18 00:59:12',
            ],
            [
                'id' => 103,
                'cabang_id' => 1,
                'barang_id' => 19,
                'jumlah' => 0,
                'created_at' => '2026-06-18 01:00:14',
                'updated_at' => '2026-06-19 13:49:59',
            ],
            [
                'id' => 104,
                'cabang_id' => 2,
                'barang_id' => 19,
                'jumlah' => 0,
                'created_at' => '2026-06-18 01:00:14',
                'updated_at' => '2026-06-18 01:00:14',
            ],
            [
                'id' => 105,
                'cabang_id' => 3,
                'barang_id' => 19,
                'jumlah' => 50,
                'created_at' => '2026-06-18 01:00:14',
                'updated_at' => '2026-06-18 01:20:08',
            ],
            [
                'id' => 106,
                'cabang_id' => 4,
                'barang_id' => 19,
                'jumlah' => 0,
                'created_at' => '2026-06-18 01:00:14',
                'updated_at' => '2026-06-18 01:00:14',
            ],
            [
                'id' => 107,
                'cabang_id' => 5,
                'barang_id' => 19,
                'jumlah' => 0,
                'created_at' => '2026-06-18 01:00:14',
                'updated_at' => '2026-06-18 01:00:14',
            ],
            [
                'id' => 108,
                'cabang_id' => 6,
                'barang_id' => 19,
                'jumlah' => 0,
                'created_at' => '2026-06-18 01:00:14',
                'updated_at' => '2026-06-18 01:00:14',
            ],
            [
                'id' => 109,
                'cabang_id' => 7,
                'barang_id' => 19,
                'jumlah' => 0,
                'created_at' => '2026-06-18 01:00:14',
                'updated_at' => '2026-06-18 01:00:14',
            ],
            [
                'id' => 110,
                'cabang_id' => 8,
                'barang_id' => 19,
                'jumlah' => 0,
                'created_at' => '2026-06-18 01:00:14',
                'updated_at' => '2026-06-18 01:00:14',
            ],
            [
                'id' => 111,
                'cabang_id' => 1,
                'barang_id' => 20,
                'jumlah' => 0,
                'created_at' => '2026-06-20 12:54:45',
                'updated_at' => '2026-06-20 12:54:45',
            ],
            [
                'id' => 112,
                'cabang_id' => 2,
                'barang_id' => 20,
                'jumlah' => 0,
                'created_at' => '2026-06-20 12:54:45',
                'updated_at' => '2026-06-20 12:54:45',
            ],
            [
                'id' => 113,
                'cabang_id' => 3,
                'barang_id' => 20,
                'jumlah' => 0,
                'created_at' => '2026-06-20 12:54:45',
                'updated_at' => '2026-06-20 12:54:45',
            ],
            [
                'id' => 114,
                'cabang_id' => 4,
                'barang_id' => 20,
                'jumlah' => 0,
                'created_at' => '2026-06-20 12:54:45',
                'updated_at' => '2026-06-20 12:54:45',
            ],
            [
                'id' => 115,
                'cabang_id' => 5,
                'barang_id' => 20,
                'jumlah' => 0,
                'created_at' => '2026-06-20 12:54:45',
                'updated_at' => '2026-06-20 12:54:45',
            ],
            [
                'id' => 116,
                'cabang_id' => 6,
                'barang_id' => 20,
                'jumlah' => 0,
                'created_at' => '2026-06-20 12:54:45',
                'updated_at' => '2026-06-20 12:54:45',
            ],
            [
                'id' => 117,
                'cabang_id' => 7,
                'barang_id' => 20,
                'jumlah' => 0,
                'created_at' => '2026-06-20 12:54:45',
                'updated_at' => '2026-06-20 13:58:37',
            ],
            [
                'id' => 118,
                'cabang_id' => 8,
                'barang_id' => 20,
                'jumlah' => 0,
                'created_at' => '2026-06-20 12:54:45',
                'updated_at' => '2026-06-20 12:54:45',
            ],
        ]);

        DB::table('stokgudang')->insert([
            [
                'id' => 4,
                'barang_id' => 7,
                'jumlah' => 725,
                'created_at' => '2026-06-15 17:44:19',
                'updated_at' => '2026-06-20 14:02:04',
            ],
            [
                'id' => 5,
                'barang_id' => 8,
                'jumlah' => 125,
                'created_at' => '2026-06-15 17:44:31',
                'updated_at' => '2026-06-21 17:07:47',
            ],
            [
                'id' => 6,
                'barang_id' => 9,
                'jumlah' => 865,
                'created_at' => '2026-06-16 07:40:37',
                'updated_at' => '2026-06-22 20:08:15',
            ],
            [
                'id' => 7,
                'barang_id' => 10,
                'jumlah' => 495,
                'created_at' => '2026-06-16 07:41:51',
                'updated_at' => '2026-06-26 14:11:30',
            ],
            [
                'id' => 8,
                'barang_id' => 11,
                'jumlah' => 40,
                'created_at' => '2026-06-16 07:42:48',
                'updated_at' => '2026-06-18 13:21:10',
            ],
            [
                'id' => 9,
                'barang_id' => 12,
                'jumlah' => 30,
                'created_at' => '2026-06-16 07:43:23',
                'updated_at' => '2026-06-22 16:07:26',
            ],
            [
                'id' => 11,
                'barang_id' => 14,
                'jumlah' => 50,
                'created_at' => '2026-06-18 00:56:21',
                'updated_at' => '2026-06-20 10:00:33',
            ],
            [
                'id' => 12,
                'barang_id' => 15,
                'jumlah' => 80,
                'created_at' => '2026-06-18 00:56:55',
                'updated_at' => '2026-06-18 13:21:10',
            ],
            [
                'id' => 13,
                'barang_id' => 16,
                'jumlah' => 5430,
                'created_at' => '2026-06-18 00:57:43',
                'updated_at' => '2026-06-22 16:07:26',
            ],
            [
                'id' => 14,
                'barang_id' => 17,
                'jumlah' => 300,
                'created_at' => '2026-06-18 00:58:09',
                'updated_at' => '2026-06-20 13:43:25',
            ],
            [
                'id' => 15,
                'barang_id' => 18,
                'jumlah' => 259,
                'created_at' => '2026-06-18 00:59:11',
                'updated_at' => '2026-06-20 14:00:14',
            ],
            [
                'id' => 16,
                'barang_id' => 19,
                'jumlah' => 300,
                'created_at' => '2026-06-18 01:00:14',
                'updated_at' => '2026-06-21 18:18:49',
            ],
            [
                'id' => 17,
                'barang_id' => 20,
                'jumlah' => 400,
                'created_at' => '2026-06-20 12:54:45',
                'updated_at' => '2026-06-23 12:12:56',
            ],
        ]);

        DB::table('stokkeluar')->insert([
            [
                'id' => 3,
                'cabang_id' => 1,
                'user_id' => 2,
                'kodekeluar' => 'SK20260615174702',
                'created_at' => '2026-06-15 17:47:02',
                'updated_at' => '2026-06-15 17:47:02',
                'catatan' => null,
            ],
            [
                'id' => 4,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SKG20260617163350',
                'created_at' => '2026-06-17 16:33:50',
                'updated_at' => '2026-06-17 16:33:50',
                'catatan' => null,
            ],
            [
                'id' => 5,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SKG20260617165315',
                'created_at' => '2026-06-17 16:53:15',
                'updated_at' => '2026-06-17 16:53:15',
                'catatan' => null,
            ],
            [
                'id' => 7,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260617-0003',
                'created_at' => '2026-06-17 17:12:37',
                'updated_at' => '2026-06-17 17:12:37',
                'catatan' => 'exp',
            ],
            [
                'id' => 8,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260617-0004',
                'created_at' => '2026-06-17 17:22:05',
                'updated_at' => '2026-06-17 17:22:05',
                'catatan' => 'exp',
            ],
            [
                'id' => 9,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260617-0005',
                'created_at' => '2026-06-17 17:56:21',
                'updated_at' => '2026-06-17 17:56:21',
                'catatan' => 'exp',
            ],
            [
                'id' => 10,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260618-0001',
                'created_at' => '2026-06-18 01:01:32',
                'updated_at' => '2026-06-18 01:01:32',
                'catatan' => 'Exp',
            ],
            [
                'id' => 11,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260618-0002',
                'created_at' => '2026-06-18 01:32:59',
                'updated_at' => '2026-06-18 01:32:59',
                'catatan' => 'Pengeluaran otomatis dari permintaan disetujui (ID Permintaan: 16)',
            ],
            [
                'id' => 12,
                'cabang_id' => 1,
                'user_id' => 2,
                'kodekeluar' => 'SK202606180003',
                'created_at' => '2026-06-18 02:38:55',
                'updated_at' => '2026-06-18 02:38:55',
                'catatan' => 'Dikurangi Kasir via Modal: terjual',
            ],
            [
                'id' => 13,
                'cabang_id' => 1,
                'user_id' => 2,
                'kodekeluar' => 'SK202606180004',
                'created_at' => '2026-06-18 02:39:17',
                'updated_at' => '2026-06-18 02:39:17',
                'catatan' => 'Dikurangi Kasir via Modal: terjual',
            ],
            [
                'id' => 14,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260618-0005',
                'created_at' => '2026-06-18 03:14:51',
                'updated_at' => '2026-06-18 03:14:51',
                'catatan' => 'Pengeluaran otomatis (Admin) dari permintaan disetujui (ID Permintaan: 17)',
            ],
            [
                'id' => 15,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260618-0006',
                'created_at' => '2026-06-18 04:44:47',
                'updated_at' => '2026-06-18 04:44:47',
                'catatan' => 'EXP',
            ],
            [
                'id' => 16,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260618-0007',
                'created_at' => '2026-06-18 04:50:52',
                'updated_at' => '2026-06-18 04:50:52',
                'catatan' => 'Pengeluaran otomatis dari permintaan disetujui (ID Permintaan: 18)',
            ],
            [
                'id' => 17,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260618-0008',
                'created_at' => '2026-06-18 13:21:10',
                'updated_at' => '2026-06-18 13:21:10',
                'catatan' => 'Pengeluaran otomatis (Admin) dari permintaan disetujui (ID Permintaan: 21)',
            ],
            [
                'id' => 18,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260618-0009',
                'created_at' => '2026-06-18 13:29:46',
                'updated_at' => '2026-06-18 13:29:46',
                'catatan' => 'EXP',
            ],
            [
                'id' => 19,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260618-0010',
                'created_at' => '2026-06-18 13:34:37',
                'updated_at' => '2026-06-18 13:34:37',
                'catatan' => 'Pengeluaran otomatis dari permintaan disetujui (ID Permintaan: 22)',
            ],
            [
                'id' => 20,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260619-0001',
                'created_at' => '2026-06-19 13:39:39',
                'updated_at' => '2026-06-19 13:39:39',
                'catatan' => 'exp',
            ],
            [
                'id' => 21,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260619-0002',
                'created_at' => '2026-06-19 13:40:06',
                'updated_at' => '2026-06-19 13:40:06',
                'catatan' => 'exp',
            ],
            [
                'id' => 22,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260619-0003',
                'created_at' => '2026-06-19 13:40:27',
                'updated_at' => '2026-06-19 13:40:27',
                'catatan' => 'exp',
            ],
            [
                'id' => 23,
                'cabang_id' => 1,
                'user_id' => 2,
                'kodekeluar' => 'SK202606190004',
                'created_at' => '2026-06-19 13:49:59',
                'updated_at' => '2026-06-19 13:49:59',
                'catatan' => 'Dikurangi Kasir via Modal: s',
            ],
            [
                'id' => 24,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260619-0005',
                'created_at' => '2026-06-19 19:29:50',
                'updated_at' => '2026-06-19 19:29:50',
                'catatan' => 'Pengeluaran otomatis dari permintaan disetujui (ID Permintaan: 23)',
            ],
            [
                'id' => 25,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260619-0006',
                'created_at' => '2026-06-19 19:32:59',
                'updated_at' => '2026-06-19 19:32:59',
                'catatan' => 'Pengeluaran otomatis dari permintaan disetujui (ID Permintaan: 24)',
            ],
            [
                'id' => 26,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260620-0001',
                'created_at' => '2026-06-20 09:49:44',
                'updated_at' => '2026-06-20 09:49:44',
                'catatan' => 'Pengeluaran otomatis dari permintaan disetujui (ID Permintaan: 25)',
            ],
            [
                'id' => 27,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260620-0002',
                'created_at' => '2026-06-20 10:00:33',
                'updated_at' => '2026-06-20 10:00:33',
                'catatan' => 'Pengeluaran otomatis dari permintaan disetujui (ID Permintaan: 26)',
            ],
            [
                'id' => 28,
                'cabang_id' => 1,
                'user_id' => 2,
                'kodekeluar' => 'SK202606200003',
                'created_at' => '2026-06-20 11:05:45',
                'updated_at' => '2026-06-20 11:05:45',
                'catatan' => 'Dikurangi Kasir via Modal: terjual',
            ],
            [
                'id' => 29,
                'cabang_id' => 1,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260620-0004',
                'created_at' => '2026-06-20 11:07:37',
                'updated_at' => '2026-06-20 11:07:37',
                'catatan' => 'Pengeluaran otomatis dari permintaan disetujui (ID Permintaan: 28)',
            ],
            [
                'id' => 30,
                'cabang_id' => 1,
                'user_id' => 2,
                'kodekeluar' => 'SK202606200005',
                'created_at' => '2026-06-20 11:45:48',
                'updated_at' => '2026-06-20 11:45:48',
                'catatan' => 'Dikurangi Kasir via Modal: terjual',
            ],
            [
                'id' => 31,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260620-0006',
                'created_at' => '2026-06-20 11:52:57',
                'updated_at' => '2026-06-20 11:52:57',
                'catatan' => 'exp',
            ],
            [
                'id' => 32,
                'cabang_id' => 3,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260620-0007',
                'created_at' => '2026-06-20 11:55:23',
                'updated_at' => '2026-06-20 11:55:23',
                'catatan' => 'Pengeluaran otomatis dari permintaan disetujui (ID Permintaan: 29)',
            ],
            [
                'id' => 33,
                'cabang_id' => 1,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260620-0008',
                'created_at' => '2026-06-20 12:32:57',
                'updated_at' => '2026-06-20 12:32:57',
                'catatan' => 'Pengeluaran otomatis dari permintaan disetujui (ID Permintaan: 30)',
            ],
            [
                'id' => 34,
                'cabang_id' => 7,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260620-0009',
                'created_at' => '2026-06-20 13:40:33',
                'updated_at' => '2026-06-20 13:40:33',
                'catatan' => 'Pengeluaran otomatis dari permintaan disetujui (ID Permintaan: 31)',
            ],
            [
                'id' => 35,
                'cabang_id' => 7,
                'user_id' => 7,
                'kodekeluar' => 'SK202606200010',
                'created_at' => '2026-06-20 13:58:37',
                'updated_at' => '2026-06-20 13:58:37',
                'catatan' => 'Dikurangi Kasir via Modal: terjual',
            ],
            [
                'id' => 36,
                'cabang_id' => 7,
                'user_id' => 7,
                'kodekeluar' => 'SK202606200011',
                'created_at' => '2026-06-20 13:58:55',
                'updated_at' => '2026-06-20 13:58:55',
                'catatan' => 'Dikurangi Kasir via Modal: terjual',
            ],
            [
                'id' => 37,
                'cabang_id' => 7,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260620-0012',
                'created_at' => '2026-06-20 14:00:14',
                'updated_at' => '2026-06-20 14:00:14',
                'catatan' => 'Pengeluaran otomatis dari permintaan disetujui (ID Permintaan: 32)',
            ],
            [
                'id' => 38,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260620-0013',
                'created_at' => '2026-06-20 14:03:55',
                'updated_at' => '2026-06-20 14:03:55',
                'catatan' => 'exp',
            ],
            [
                'id' => 39,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260621-0001',
                'created_at' => '2026-06-21 18:18:49',
                'updated_at' => '2026-06-21 18:18:49',
                'catatan' => 'exp',
            ],
            [
                'id' => 40,
                'cabang_id' => 7,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260622-0001',
                'created_at' => '2026-06-22 16:07:26',
                'updated_at' => '2026-06-22 16:07:26',
                'catatan' => 'Pengeluaran otomatis dari permintaan disetujui (ID Permintaan: 38)',
            ],
            [
                'id' => 41,
                'cabang_id' => 7,
                'user_id' => 7,
                'kodekeluar' => 'SK202606220002',
                'created_at' => '2026-06-22 16:32:51',
                'updated_at' => '2026-06-22 16:32:51',
                'catatan' => 'Dikurangi Kasir via Modal: Barang tidak sampai',
            ],
            [
                'id' => 42,
                'cabang_id' => null,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260623-0001',
                'created_at' => '2026-06-23 12:12:56',
                'updated_at' => '2026-06-23 12:12:56',
                'catatan' => 'EXP',
            ],
            [
                'id' => 43,
                'cabang_id' => 7,
                'user_id' => 7,
                'kodekeluar' => 'SK202606230002',
                'created_at' => '2026-06-23 12:19:37',
                'updated_at' => '2026-06-23 12:19:37',
                'catatan' => 'Dikurangi Kasir via Modal: Terpakai',
            ],
            [
                'id' => 44,
                'cabang_id' => 7,
                'user_id' => 7,
                'kodekeluar' => 'SK202606230003',
                'created_at' => '2026-06-23 12:23:01',
                'updated_at' => '2026-06-23 12:23:01',
                'catatan' => 'Dikurangi Kasir via Modal: Terpakai',
            ],
            [
                'id' => 45,
                'cabang_id' => 7,
                'user_id' => 1,
                'kodekeluar' => 'SK-20260626-0001',
                'created_at' => '2026-06-26 14:11:30',
                'updated_at' => '2026-06-26 14:11:30',
                'catatan' => 'Pengeluaran otomatis dari permintaan disetujui (ID Permintaan: 39)',
            ],
        ]);

        DB::table('stokkeluardetail')->insert([
            [
                'id' => 3,
                'stokkeluar_id' => 3,
                'stokcabang_id' => 7,
                'jumlah' => 10,
                'barang_id' => 0,
            ],
            [
                'id' => 4,
                'stokkeluar_id' => 3,
                'stokcabang_id' => 9,
                'jumlah' => 10,
                'barang_id' => 0,
            ],
            [
                'id' => 5,
                'stokkeluar_id' => 4,
                'stokcabang_id' => 9,
                'jumlah' => 8,
                'barang_id' => 0,
            ],
            [
                'id' => 6,
                'stokkeluar_id' => 5,
                'stokcabang_id' => 39,
                'jumlah' => 30,
                'barang_id' => 0,
            ],
            [
                'id' => 7,
                'stokkeluar_id' => 7,
                'stokcabang_id' => null,
                'jumlah' => 100,
                'barang_id' => 12,
            ],
            [
                'id' => 8,
                'stokkeluar_id' => 8,
                'stokcabang_id' => null,
                'jumlah' => 10,
                'barang_id' => 11,
            ],
            [
                'id' => 9,
                'stokkeluar_id' => 9,
                'stokcabang_id' => null,
                'jumlah' => 100,
                'barang_id' => 12,
            ],
            [
                'id' => 10,
                'stokkeluar_id' => 10,
                'stokcabang_id' => null,
                'jumlah' => 90,
                'barang_id' => 12,
            ],
            [
                'id' => 11,
                'stokkeluar_id' => 11,
                'stokcabang_id' => null,
                'jumlah' => 50,
                'barang_id' => 8,
            ],
            [
                'id' => 12,
                'stokkeluar_id' => 12,
                'stokcabang_id' => 31,
                'jumlah' => 10,
                'barang_id' => 10,
            ],
            [
                'id' => 13,
                'stokkeluar_id' => 13,
                'stokcabang_id' => 31,
                'jumlah' => 10,
                'barang_id' => 10,
            ],
            [
                'id' => 14,
                'stokkeluar_id' => 14,
                'stokcabang_id' => null,
                'jumlah' => 5,
                'barang_id' => 7,
            ],
            [
                'id' => 15,
                'stokkeluar_id' => 15,
                'stokcabang_id' => null,
                'jumlah' => 95,
                'barang_id' => 18,
            ],
            [
                'id' => 16,
                'stokkeluar_id' => 16,
                'stokcabang_id' => null,
                'jumlah' => 50,
                'barang_id' => 11,
            ],
            [
                'id' => 17,
                'stokkeluar_id' => 17,
                'stokcabang_id' => null,
                'jumlah' => 30,
                'barang_id' => 10,
            ],
            [
                'id' => 18,
                'stokkeluar_id' => 17,
                'stokcabang_id' => null,
                'jumlah' => 20,
                'barang_id' => 15,
            ],
            [
                'id' => 19,
                'stokkeluar_id' => 17,
                'stokcabang_id' => null,
                'jumlah' => 20,
                'barang_id' => 11,
            ],
            [
                'id' => 20,
                'stokkeluar_id' => 18,
                'stokcabang_id' => null,
                'jumlah' => 45,
                'barang_id' => 19,
            ],
            [
                'id' => 21,
                'stokkeluar_id' => 19,
                'stokcabang_id' => null,
                'jumlah' => 1,
                'barang_id' => 19,
            ],
            [
                'id' => 22,
                'stokkeluar_id' => 20,
                'stokcabang_id' => null,
                'jumlah' => 10,
                'barang_id' => 18,
            ],
            [
                'id' => 23,
                'stokkeluar_id' => 21,
                'stokcabang_id' => null,
                'jumlah' => 10,
                'barang_id' => 18,
            ],
            [
                'id' => 24,
                'stokkeluar_id' => 22,
                'stokcabang_id' => null,
                'jumlah' => 1,
                'barang_id' => 18,
            ],
            [
                'id' => 25,
                'stokkeluar_id' => 23,
                'stokcabang_id' => 103,
                'jumlah' => 1,
                'barang_id' => 19,
            ],
            [
                'id' => 26,
                'stokkeluar_id' => 24,
                'stokcabang_id' => null,
                'jumlah' => 15,
                'barang_id' => 12,
            ],
            [
                'id' => 27,
                'stokkeluar_id' => 25,
                'stokcabang_id' => null,
                'jumlah' => 500,
                'barang_id' => 10,
            ],
            [
                'id' => 28,
                'stokkeluar_id' => 26,
                'stokcabang_id' => null,
                'jumlah' => 90,
                'barang_id' => 10,
            ],
            [
                'id' => 29,
                'stokkeluar_id' => 27,
                'stokcabang_id' => null,
                'jumlah' => 100,
                'barang_id' => 17,
            ],
            [
                'id' => 30,
                'stokkeluar_id' => 27,
                'stokcabang_id' => null,
                'jumlah' => 50,
                'barang_id' => 14,
            ],
            [
                'id' => 31,
                'stokkeluar_id' => 27,
                'stokcabang_id' => null,
                'jumlah' => 10,
                'barang_id' => 10,
            ],
            [
                'id' => 32,
                'stokkeluar_id' => 28,
                'stokcabang_id' => 47,
                'jumlah' => 5,
                'barang_id' => 12,
            ],
            [
                'id' => 33,
                'stokkeluar_id' => 29,
                'stokcabang_id' => null,
                'jumlah' => 5,
                'barang_id' => 9,
            ],
            [
                'id' => 34,
                'stokkeluar_id' => 30,
                'stokcabang_id' => 31,
                'jumlah' => 20,
                'barang_id' => 10,
            ],
            [
                'id' => 35,
                'stokkeluar_id' => 31,
                'stokcabang_id' => null,
                'jumlah' => 10,
                'barang_id' => 16,
            ],
            [
                'id' => 36,
                'stokkeluar_id' => 32,
                'stokcabang_id' => null,
                'jumlah' => 50,
                'barang_id' => 12,
            ],
            [
                'id' => 37,
                'stokkeluar_id' => 33,
                'stokcabang_id' => null,
                'jumlah' => 100,
                'barang_id' => 12,
            ],
            [
                'id' => 38,
                'stokkeluar_id' => 33,
                'stokcabang_id' => null,
                'jumlah' => 100,
                'barang_id' => 16,
            ],
            [
                'id' => 39,
                'stokkeluar_id' => 34,
                'stokcabang_id' => null,
                'jumlah' => 10,
                'barang_id' => 20,
            ],
            [
                'id' => 40,
                'stokkeluar_id' => 34,
                'stokcabang_id' => null,
                'jumlah' => 20,
                'barang_id' => 9,
            ],
            [
                'id' => 41,
                'stokkeluar_id' => 35,
                'stokcabang_id' => 117,
                'jumlah' => 10,
                'barang_id' => 20,
            ],
            [
                'id' => 42,
                'stokkeluar_id' => 36,
                'stokcabang_id' => 27,
                'jumlah' => 20,
                'barang_id' => 9,
            ],
            [
                'id' => 43,
                'stokkeluar_id' => 37,
                'stokcabang_id' => null,
                'jumlah' => 100,
                'barang_id' => 10,
            ],
            [
                'id' => 44,
                'stokkeluar_id' => 37,
                'stokcabang_id' => null,
                'jumlah' => 50,
                'barang_id' => 18,
            ],
            [
                'id' => 45,
                'stokkeluar_id' => 38,
                'stokcabang_id' => null,
                'jumlah' => 590,
                'barang_id' => 20,
            ],
            [
                'id' => 46,
                'stokkeluar_id' => 39,
                'stokcabang_id' => null,
                'jumlah' => 4,
                'barang_id' => 19,
            ],
            [
                'id' => 47,
                'stokkeluar_id' => 40,
                'stokcabang_id' => null,
                'jumlah' => 5,
                'barang_id' => 12,
            ],
            [
                'id' => 48,
                'stokkeluar_id' => 40,
                'stokcabang_id' => null,
                'jumlah' => 10,
                'barang_id' => 16,
            ],
            [
                'id' => 49,
                'stokkeluar_id' => 40,
                'stokcabang_id' => null,
                'jumlah' => 15,
                'barang_id' => 10,
            ],
            [
                'id' => 50,
                'stokkeluar_id' => 41,
                'stokcabang_id' => 101,
                'jumlah' => 30,
                'barang_id' => 18,
            ],
            [
                'id' => 51,
                'stokkeluar_id' => 42,
                'stokcabang_id' => null,
                'jumlah' => 100,
                'barang_id' => 20,
            ],
            [
                'id' => 52,
                'stokkeluar_id' => 43,
                'stokcabang_id' => 37,
                'jumlah' => 15,
                'barang_id' => 10,
            ],
            [
                'id' => 53,
                'stokkeluar_id' => 44,
                'stokcabang_id' => 101,
                'jumlah' => 10,
                'barang_id' => 18,
            ],
            [
                'id' => 54,
                'stokkeluar_id' => 45,
                'stokcabang_id' => null,
                'jumlah' => 10,
                'barang_id' => 10,
            ],
        ]);

        DB::table('stokmasuk')->insert([
            [
                'id' => 4,
                'kodemasuk' => 'SM20260615174459',
                'created_at' => '2026-06-15 17:44:59',
                'updated_at' => '2026-06-15 17:44:59',
            ],
            [
                'id' => 5,
                'kodemasuk' => 'SM20260616074813',
                'created_at' => '2026-06-16 07:48:13',
                'updated_at' => '2026-06-16 07:48:13',
            ],
            [
                'id' => 6,
                'kodemasuk' => 'SM20260617160254',
                'created_at' => '2026-06-17 16:02:54',
                'updated_at' => '2026-06-17 16:02:54',
            ],
            [
                'id' => 7,
                'kodemasuk' => 'SM20260618011430',
                'created_at' => '2026-06-18 01:14:30',
                'updated_at' => '2026-06-18 01:14:30',
            ],
            [
                'id' => 8,
                'kodemasuk' => 'SM20260618042900',
                'created_at' => '2026-06-18 04:29:00',
                'updated_at' => '2026-06-18 04:29:00',
            ],
            [
                'id' => 9,
                'kodemasuk' => 'SM20260618043101',
                'created_at' => '2026-06-18 04:31:01',
                'updated_at' => '2026-06-18 04:31:01',
            ],
            [
                'id' => 10,
                'kodemasuk' => 'SM20260618132306',
                'created_at' => '2026-06-18 13:23:06',
                'updated_at' => '2026-06-18 13:23:06',
            ],
            [
                'id' => 11,
                'kodemasuk' => 'SM20260619193053',
                'created_at' => '2026-06-19 19:30:53',
                'updated_at' => '2026-06-19 19:30:53',
            ],
            [
                'id' => 12,
                'kodemasuk' => 'SM20260620094802',
                'created_at' => '2026-06-20 09:48:02',
                'updated_at' => '2026-06-20 09:48:02',
            ],
            [
                'id' => 13,
                'kodemasuk' => 'SM20260620123037',
                'created_at' => '2026-06-20 12:30:37',
                'updated_at' => '2026-06-20 12:30:37',
            ],
            [
                'id' => 14,
                'kodemasuk' => 'SM20260620125525',
                'created_at' => '2026-06-20 12:55:25',
                'updated_at' => '2026-06-20 12:55:25',
            ],
            [
                'id' => 15,
                'kodemasuk' => 'SM20260620134325',
                'created_at' => '2026-06-20 13:43:25',
                'updated_at' => '2026-06-20 13:43:25',
            ],
            [
                'id' => 16,
                'kodemasuk' => 'SM20260620140204',
                'created_at' => '2026-06-20 14:02:04',
                'updated_at' => '2026-06-20 14:02:04',
            ],
            [
                'id' => 17,
                'kodemasuk' => 'SM20260621170747',
                'created_at' => '2026-06-21 17:07:47',
                'updated_at' => '2026-06-21 17:07:47',
            ],
            [
                'id' => 18,
                'kodemasuk' => 'SM20260621171636',
                'created_at' => '2026-06-21 17:16:36',
                'updated_at' => '2026-06-21 17:16:36',
            ],
            [
                'id' => 19,
                'kodemasuk' => 'SM20260622200815',
                'created_at' => '2026-06-22 20:08:15',
                'updated_at' => '2026-06-22 20:08:15',
            ],
        ]);

        DB::table('stokmasukdetail')->insert([
            [
                'id' => 5,
                'stokmasuk_id' => 4,
                'stokgudang_id' => 4,
                'jumlah' => 100,
            ],
            [
                'id' => 6,
                'stokmasuk_id' => 4,
                'stokgudang_id' => 5,
                'jumlah' => 100,
            ],
            [
                'id' => 7,
                'stokmasuk_id' => 5,
                'stokgudang_id' => 6,
                'jumlah' => 100,
            ],
            [
                'id' => 8,
                'stokmasuk_id' => 5,
                'stokgudang_id' => 7,
                'jumlah' => 100,
            ],
            [
                'id' => 9,
                'stokmasuk_id' => 5,
                'stokgudang_id' => 8,
                'jumlah' => 50,
            ],
            [
                'id' => 10,
                'stokmasuk_id' => 5,
                'stokgudang_id' => 9,
                'jumlah' => 300,
            ],
            [
                'id' => 11,
                'stokmasuk_id' => 6,
                'stokgudang_id' => 6,
                'jumlah' => 500,
            ],
            [
                'id' => 12,
                'stokmasuk_id' => 7,
                'stokgudang_id' => 16,
                'jumlah' => 100,
            ],
            [
                'id' => 13,
                'stokmasuk_id' => 7,
                'stokgudang_id' => 15,
                'jumlah' => 100,
            ],
            [
                'id' => 14,
                'stokmasuk_id' => 7,
                'stokgudang_id' => 14,
                'jumlah' => 100,
            ],
            [
                'id' => 15,
                'stokmasuk_id' => 7,
                'stokgudang_id' => 13,
                'jumlah' => 100,
            ],
            [
                'id' => 16,
                'stokmasuk_id' => 7,
                'stokgudang_id' => 12,
                'jumlah' => 100,
            ],
            [
                'id' => 17,
                'stokmasuk_id' => 7,
                'stokgudang_id' => 9,
                'jumlah' => 100,
            ],
            [
                'id' => 18,
                'stokmasuk_id' => 7,
                'stokgudang_id' => 8,
                'jumlah' => 100,
            ],
            [
                'id' => 19,
                'stokmasuk_id' => 7,
                'stokgudang_id' => 7,
                'jumlah' => 100,
            ],
            [
                'id' => 20,
                'stokmasuk_id' => 7,
                'stokgudang_id' => 6,
                'jumlah' => 100,
            ],
            [
                'id' => 21,
                'stokmasuk_id' => 7,
                'stokgudang_id' => 5,
                'jumlah' => 100,
            ],
            [
                'id' => 22,
                'stokmasuk_id' => 7,
                'stokgudang_id' => 4,
                'jumlah' => 100,
            ],
            [
                'id' => 23,
                'stokmasuk_id' => 8,
                'stokgudang_id' => 10,
                'jumlah' => 100,
            ],
            [
                'id' => 24,
                'stokmasuk_id' => 9,
                'stokgudang_id' => 11,
                'jumlah' => 100,
            ],
            [
                'id' => 25,
                'stokmasuk_id' => 10,
                'stokgudang_id' => 15,
                'jumlah' => 25,
            ],
            [
                'id' => 26,
                'stokmasuk_id' => 11,
                'stokgudang_id' => 7,
                'jumlah' => 1000,
            ],
            [
                'id' => 27,
                'stokmasuk_id' => 12,
                'stokgudang_id' => 4,
                'jumlah' => 50,
            ],
            [
                'id' => 28,
                'stokmasuk_id' => 13,
                'stokgudang_id' => 9,
                'jumlah' => 100,
            ],
            [
                'id' => 29,
                'stokmasuk_id' => 13,
                'stokgudang_id' => 13,
                'jumlah' => 500,
            ],
            [
                'id' => 30,
                'stokmasuk_id' => 14,
                'stokgudang_id' => 17,
                'jumlah' => 100,
            ],
            [
                'id' => 31,
                'stokmasuk_id' => 15,
                'stokgudang_id' => 14,
                'jumlah' => 300,
            ],
            [
                'id' => 32,
                'stokmasuk_id' => 15,
                'stokgudang_id' => 16,
                'jumlah' => 300,
            ],
            [
                'id' => 33,
                'stokmasuk_id' => 15,
                'stokgudang_id' => 15,
                'jumlah' => 300,
            ],
            [
                'id' => 34,
                'stokmasuk_id' => 16,
                'stokgudang_id' => 4,
                'jumlah' => 500,
            ],
            [
                'id' => 35,
                'stokmasuk_id' => 16,
                'stokgudang_id' => 6,
                'jumlah' => 500,
            ],
            [
                'id' => 36,
                'stokmasuk_id' => 16,
                'stokgudang_id' => 17,
                'jumlah' => 500,
            ],
            [
                'id' => 37,
                'stokmasuk_id' => 17,
                'stokgudang_id' => 5,
                'jumlah' => 10,
            ],
            [
                'id' => 38,
                'stokmasuk_id' => 18,
                'stokgudang_id' => 13,
                'jumlah' => 5000,
            ],
            [
                'id' => 39,
                'stokmasuk_id' => 19,
                'stokgudang_id' => 6,
                'jumlah' => 100,
            ],
            [
                'id' => 40,
                'stokmasuk_id' => 19,
                'stokgudang_id' => 17,
                'jumlah' => 500,
            ],
            [
                'id' => 41,
                'stokmasuk_id' => 19,
                'stokgudang_id' => 7,
                'jumlah' => 100,
            ],
        ]);

        DB::table('users')->insert([
            [
                'id' => 1,
                'cabang_id' => 0,
                'name' => 'Administrator',
                'email' => 'admin@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$ZtN9vXyjrGGu/jRTYc7Ta.m5KlWXfE.ExUbuu1lbdRajcUiiO55dS',
                'role' => 'Admin',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2,
                'cabang_id' => 1,
                'name' => 'Usman',
                'email' => 'usman@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$wGc3zbzGm12QAls8k2p02uor0IPfP0am4Kn2MLDc/M1lryYTkR02u',
                'role' => 'Kasir',
                'remember_token' => null,
                'created_at' => '2026-06-14 22:28:31',
                'updated_at' => '2026-06-15 15:56:09',
            ],
            [
                'id' => 3,
                'cabang_id' => null,
                'name' => 'Gudang',
                'email' => 'gudang@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$LP1qxuBmHQjjWLiFaxfV3e0F7xhAIq2cjvCs2AWXB/NNjYdwLX/M.',
                'role' => 'Gudang',
                'remember_token' => null,
                'created_at' => '2026-06-14 22:29:17',
                'updated_at' => '2026-06-16 00:44:17',
            ],
            [
                'id' => 4,
                'cabang_id' => 0,
                'name' => 'sandy',
                'email' => 'sandy@gmail.com',
                'email_verified_at' => null,
                'password' => 'sandy123',
                'role' => 'admin',
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 5,
                'cabang_id' => 2,
                'name' => 'ucup',
                'email' => 'Ucup@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$GG8CfnZEoST9ZXjCsYQNLuTB24PXT7i3qetgt47RWlxBYAqgJReGO',
                'role' => 'Kasir',
                'remember_token' => null,
                'created_at' => '2026-06-16 00:55:55',
                'updated_at' => '2026-06-16 00:55:55',
            ],
            [
                'id' => 6,
                'cabang_id' => 3,
                'name' => 'Yogi',
                'email' => 'Yogi@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$QvcRZOOP3xL.EaHT0cKrhOQhKn/hM1FNnDK2QAJ5qCog2Aus2y0uC',
                'role' => 'Kasir',
                'remember_token' => null,
                'created_at' => '2026-06-16 00:56:56',
                'updated_at' => '2026-06-16 00:56:56',
            ],
            [
                'id' => 7,
                'cabang_id' => 7,
                'name' => 'sandy',
                'email' => 'sandy@rmpuring.com',
                'email_verified_at' => null,
                'password' => '$2y$12$hT6E5r2MeXdOM2hvTpVoPughtzSV8J1v0h0qPog1eZZ6InScPJ90e',
                'role' => 'Kasir',
                'remember_token' => null,
                'created_at' => '2026-06-20 06:34:32',
                'updated_at' => '2026-06-20 06:34:32',
            ],
        ]);

        $this->command->info('Data manual berhasil di-seed.');
    }
}
